Feat/interaction table map
naturerobots/HSOS-SEP-PlantMap-2022 pull request #139
Opened 2022-06-22 14:51 UTC by fmarahre

hover-interaction **table<-->map** works in `CropsView.vue` and `Crops3dView.vue`

2022-06-22 19:54 UTC, dobro929 commented on vue/src/views/Crops3dView.vue
>    </div>
added view wrapper
```suggestion
  <div class="ml-28">
    <header-bar
      title="3D"
      :widgetOptions="widgetOptions3D"
      :storeOptions="storeOptions"
    ></header-bar>
    <div class="row p-6">
      <div v-if="storeOptions.indexOf('3d-table') > -1" class="col-4">
        <crops-table
          ref="cropsTableRef"
          title="Plants"
          :visibleColumns="columns"
          :crops="crops"
          @row-enter="tableCropsEnter"
          @row-leave="tableCropsLeave"
        ></crops-table>
      </div>
      <div v-if="storeOptions.indexOf('3d-map') > -1" class="col-8 pl-2">
        <crops-map
          ref="cropsMapRef"
          :crops="crops"
          @polygon-enter="mapCropsEnter"
          @polygon-leave="mapCropsLeave"
        ></crops-map>
      </div>
    </div>
  </div>
```

2022-06-22 19:54 UTC, dobro929 commented on vue/src/views/CropsView.vue
>    </div>
added view wrapper
```suggestion
  <div class="ml-28">
    <header-bar
      title="Crops"
      :widgetOptions="widgetOptionsCrops"
      :storeOptions="storeOptions"
    ></header-bar>
    <div class="row p-6">
      <div v-if="storeOptions.indexOf('crops-table') > -1" class="col-8">
        <crops-table
          ref="cropsTableRef"
          title="Overview"
          :crops="crops"
          :visibleColumns="columns"
          @row-enter="tableCropsEnter"
          @row-leave="tableCropsLeave"
        ></crops-table>
      </div>
      <div v-if="storeOptions.indexOf('crops-map') > -1" class="col-4 pl-2">
        <crops-map
          ref="cropsMapRef"
          :crops="crops"
          @polygon-enter="mapCropsEnter"
          @polygon-leave="mapCropsLeave"
        ></crops-map>
      </div>
    </div>
  </div>
```

2022-06-22 19:54 UTC, dobro929 commented on vue/src/views/CropsView.vue
> +import { onMounted, type Ref, ref } from "vue";
removed unused import
```suggestion
import { type Ref, ref } from "vue";
```

2022-06-22 19:54 UTC, dobro929 commented on vue/src/views/Crops3dView.vue
> +import { onMounted, type Ref, ref } from "vue";
removed unused import
```suggestion
import { type Ref, ref } from "vue";
```

2022-06-23 07:54 UTC, lucaslootalot requested changes

2022-06-23 07:54 UTC, lucaslootalot commented on vue/src/components/CropsTable.vue
> +function pagination() {
add return type

2022-06-25 11:57 UTC, fmarahre commented on vue/src/components/CropsTable.vue
> +function pagination() {
done

2022-06-25 13:39 UTC, lucaslootalot approved these changes
lgtm, i will squash the commits and then you can merge the PR 👍🏻

2022-06-25 15:04 UTC, merged