feat/basemap create
naturerobots/HSOS-SEP-PlantMap-2022 pull request #94
Opened 2022-06-02 15:07 UTC by dobro929

- created `BaseMap.vue` and `CropsMap.vue` component
- fixed `LeafletComp.vue`
- integrated `LeafletComp.vue` in `BaseMap.vue`
- added `BaseMap.vue` into `CropsMap.vue` and `GardenMap.vue` with **mock data**

2022-06-02 16:00 UTC, lucaslootalot requested changes
See review comments.

2022-06-02 16:03 UTC, dobro929 commented on vue/src/components/BaseMap.vue
> +    type: Number,
The default values are defined in the `LeafletComp.vue`.

2022-06-02 16:06 UTC, dobro929 commented on vue/src/components/CropsMap.vue
> +const mapImage: MapImage = {
We will replace this in no time anyway

2022-06-02 18:17 UTC, lucaslootalot commented on vue/src/components/BaseMap.vue
> +    type: Number,
If they are all defined in `LeafletComp.vue` and therefore probably required without a default value, wouldn't it make sense to use "type-based declaration"?

2022-06-02 18:24 UTC, lucaslootalot commented on vue/src/components/BaseMap.vue
> +    type: Number,
See last comment.

2022-06-03 08:54 UTC, dobro929 commented on vue/src/components/BaseMap.vue
> +    type: Number,
No, we only need `mapImage` as **required** prop. `maxZoom` and `zoom` should be **optional**.

2022-06-03 09:21 UTC, lucaslootalot commented on vue/src/components/BaseMap.vue
> +});
@dobro929 Since `maxZoom `and `zoom` are optional, I would implement the props that way.

2022-06-03 09:37 UTC, dobro929 commented on vue/src/components/BaseMap.vue
> +});
Please make binding suggestions that are **100% correct**. `PropType` import must be removed. This compiles to the **same result**, but we can make these changes.

2022-06-03 09:38 UTC, dobro929 commented on vue/src/components/Leaflet/LeafletComp.vue
> +    //Not the best solution
updated

2022-06-03 09:41 UTC, lucaslootalot commented on vue/src/components/BaseMap.vue
> +});
Ur right, i will remove the import. Yes, the result is the same, but it looks much cleaner.

2022-06-03 09:44 UTC, lucaslootalot requested changes

2022-06-03 09:44 UTC, lucaslootalot commented on vue/src/components/BaseMap.vue
> +import type { PropType } from "vue";
```suggestion
```

2022-06-03 10:01 UTC, lucaslootalot approved these changes

2022-06-03 10:03 UTC, merged